name: "master-backend"

networks:
  master-network:
    driver: bridge

services:
  nest:
    build:
      context: .
      args:
        - BACKEND_PORT=${MASTER_BACKEND_PORT}
      dockerfile: Dockerfile
    ports:
      - "${MASTER_BACKEND_PORT}:${MASTER_BACKEND_PORT}"
    depends_on:
      - database
    networks:
      - master-network

  database:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    command: -p ${DATABASE_PORT}
    networks:
      - master-network
