name: ci
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - production

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
